### ISSUE TITLE
i-sqlite cannot load sqlite database (at least on macos)

### ISSUE THREAD

**Issue by patrixl** [Shirakumo/radiance-contribs#6]
Hi,

Trying to use Radiance with i-sqlite, on macOS. I have no idea if the behavior is the same on Linux, I will try another time.

I have a potential fix (in Radiance's environment.lisp) but first I'd like to discuss and raise the issue.

Essentially, when i-sqlite tries to load `~/.config/radiance/ccdev/i-sqlite/radiance.db` (`ccdev` is the name of the environment), it complains it cannot open the db (see error below). 

However if, in environment.lisp, I replace the expression with one that fully expands `~` into `/Users/patrix`,  then i-sqlite will be able to load the database (and then I run into another issue, which I will raise separately).

I've tested this behavior directly with cl-sqlite using `connect`, and it definitely can connect using the full path but not with the `~` substitute for my home directory.

```
(SQLITE:SQLITE-ERROR :CANTOPEN ("Could not open sqlite3 database ~A" "~/.config/radiance/ccdev/i-sqlite/radiance.db") :STATEMENT NIL :DB-HANDLE NIL :SQL-TEXT NIL)
   source: (ERROR
            (IF (EQ ERROR-CODE :CONSTRAINT)
                'SQLITE-CONSTRAINT-ERROR
                'SQLITE-ERROR)
            :FORMAT-CONTROL
            (IF (LISTP MESSAGE)
                (FIRST MESSAGE)
                MESSAGE)
            :FORMAT-ARGUMENTS
            (IF (LISTP MESSAGE)
                (REST MESSAGE))
            :DB-HANDLE DB-HANDLE :ERROR-CODE ERROR-CODE :ERROR-MSG
            (IF (AND DB-HANDLE ERROR-CODE)
                (SQLITE-FFI:SQLITE3-ERRMSG (HANDLE DB-HANDLE)))
            ...)
```

My current workaround replaces line 22 of Radiance's environment.lisp with

```
(make-pathname :directory `(:absolute ,(directory-namestring (user-homedir-pathname)) ".config")))))
```

But I wonder if there's a better way...

**Comment by Shinmera** [comment]
Hi, thanks for the report. The real fix for this should be in cl-sqlite, the underlying DB library, as it seems to not handle CL pathnames quite correctly. However, as it appears it's out of maintenance, I guess a hack is necessary.

**Comment by patrixl** [comment]
Tested, and it's working now, thanks!
