### ISSUE TITLE
i-postmodern configuration

### ISSUE THREAD

**Issue by GertThiel** [Shirakumo/radiance-contribs#9]
I got the impression that my `i-postmodern.conf.lisp` is _structurally_ wrong:

```
; meta (:version 1.0 :package "I-POSTMODERN")
[hash-table equal (:enabled (:default))
 (:default
  (:connections "tfb"
   (:host "tfb-database" :port 5432 :database "hello_world" :user
    "benchmarkdbuser" :pass "benchmarkdbpass")))]
```

How does such a file should look like?

**Comment by GertThiel** [comment]
And can I abuse `i-postmodern`'s connection for plain postmodern instructions like `(postmodern:query (:select 'id 'message :from 'fortune) :rows))` for a simpler head start?

**Comment by Shinmera** [comment]
A proper config could look like this:
```
[hash-table equal
 (:default "tfb")
 (:connections
  [hash-table equal
   ("tfb"
    [hash-table equal
     (:host "tfb-database") (:port 5432)  (:database "hello_world")
     (:user "benchmarkuser") (:pass "benchmarkdbpass")])])]
```
Typically you should be able to create the proper configuration file by using [`(setf mconfig)`](https://shirakumo.github.io/radiance/#FUNCTION%20RADIANCE-CORE%3AMCONFIG) with `i-postmodern` on the fields described in the [readme](https://github.com/Shirakumo/radiance-contribs/tree/master/i-postmodern#how-to).

You can use i-postmodern's connection once it is started up and if you wrap things in `i-postmodern::with-connection`.

**Comment by GertThiel** [comment]
Thanks a lot. I just got the Radiance benchmark going albeit without idiomatic `db` or `dm` use.
